stage('Test') {
    steps {
        // 1. Lancement des tests unitaires [cite: 24]
        // Runs the standard Gradle test task
        bat './gradlew test'
    }
    post {
        always {
            // 2. Archivage des résultats des tests unitaires [cite: 25]
            // Archives the XML files generated by JUnit
            junit 'build/test-results/test/*.xml'

            // 3. Génération des rapports de tests Cucumber [cite: 26]
            // Uses the "Cucumber reports" plugin you installed [cite: 59]
            // Make sure your Cucumber runner outputs JSON to this path
            cucumber 'build/reports/cucumber/*.json'
        }
    }
}